#!/bin/bash
# This script helps to re-assemble tokens back to man pages.

process() {
  while read -r LINE; do
    [ -z "$LINE" ] && { echo; continue; }
    sed 's/^[^:]*: |\||$//g' <<<"$LINE" | tr -d '\n'
  done
}

[ -z "$1" ] && process || { cat "$1" | process; }
