#!/bin/bash
# This script helps to verify re-assembled man pages from tokens.
#
# Copyright (C) 2017  LCTT
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

DIFF_RESULT="$(diff -qrs man-pages-source/ man-pages-manual/ \
             | grep 'man-pages-[^/]*/man[0-9]')"

print_result() { printf "  %-6s : %6d  \n" "$1" "$2"; }

N_PASS="$(grep ' are identical$' <<<"$DIFF_RESULT" | wc -l)"
N_FAIL="$(grep ' differ$' <<<"$DIFF_RESULT" | wc -l)"
N_ERROR="$(grep '^Only in ' <<<"$DIFF_RESULT" | wc -l)"
N_TOTAL="$(wc -l <<<"$DIFF_RESULT")"

echo "==================="
echo "    TEST RESULT    "
echo "-------------------"
print_result "PASS"  "$N_PASS"
print_result "FAIL"  "$N_FAIL"
print_result "ERROR" "$N_ERROR"
echo "-------------------"
print_result "TOTAL" "$N_TOTAL"
echo "==================="

test "$N_PASS" = "$N_TOTAL"
