#!/bin/bash
# This script helps to re-assemble tokens back to man pages.

set -e

process() {
  tr '\n' '\r' | perl -pe 's/[^\r:]*: \|(.*?)\|\r/\1/g' | tr '\r' '\n'
}

[ -z "$1" ] && process || { cat "$1" | process; }
