#!/bin/bash
# This script helps to re-assemble tokens back to man pages.
#
# Copyright (C) 2017  LCTT
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

process() {
  tr '\n' '\r' | perl -pe 's/[^\r:]*: \|(.*?)\|\r/\1/g' | tr '\r' '\n'
}

[ -z "$1" ] && process || { cat "$1" | process; }
